const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const get=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}},set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const state={listings:get('autodeal.listings',window.AUTO_DEAL_DEFAULT_LISTINGS),searches:get('autodeal.searches',[]),saved:get('autodeal.saved',[]),ignored:get('autodeal.ignored',[]),alerts:get('autodeal.alerts',[{title:'AutoDeal מוכן',text:'צור חיפוש כדי להתחיל לעקוב אחרי רכבים.',time:'עכשיו'}]),history:get('autodeal.history',[]),settings:get('autodeal.settings',{serverUrl:''})};
const save=()=>Object.entries(state).forEach(([k,v])=>set('autodeal.'+k,v));
const money=v=>new Intl.NumberFormat('he-IL',{style:'currency',currency:'ILS',maximumFractionDigits:0}).format(+v||0),num=v=>new Intl.NumberFormat('he-IL').format(+v||0);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const discount=l=>l.referencePrice?((l.referencePrice-l.price)/l.referencePrice*100):0;
function toast(t){$('#toast').textContent=t;$('#toast').classList.remove('hidden');setTimeout(()=>$('#toast').classList.add('hidden'),2200)}
function carArt(){return `<svg viewBox="0 0 520 240" xmlns="http://www.w3.org/2000/svg"><rect width="520" height="240" fill="#16314d"/><path d="M90 166l55-78h220l55 78h28v31H64v-31z" fill="#59d0ff"/><path d="M177 104h151l35 48H143z" fill="#10233a"/><circle cx="145" cy="193" r="30" fill="#07111f"/><circle cx="374" cy="193" r="30" fill="#07111f"/></svg>`}
function card(l){const d=discount(l);return `<article class="card"><div class="car-image">${carArt()}<span class="badge">${esc(l.status||'מודעה')}</span><span class="score">${l.score||'-'}</span></div><div class="card-body"><div class="car-title"><div><h3><bdi>${esc(l.make)} ${esc(l.model)}</bdi></h3><div class="muted small">${esc(l.trim||'')}</div></div><div class="price">${money(l.price)}</div></div><div class="meta"><span>${l.year||'-'}</span><span>${num(l.mileage)} ק"מ</span><span>יד ${l.hand||'-'}</span><span>${esc(l.location||'')}</span><span>${esc(l.seller||'')}</span></div><div class="analysis"><span class="${d>=0?'positive':'negative'}">${Math.abs(d).toFixed(1)}% ${d>=0?'מתחת':'מעל'} למחירון</span>. ציון העסקה מבוסס על מחיר, שנתון וקילומטראז'.</div><div class="card-actions"><button class="btn primary" onclick="details('${esc(l.id)}')">פרטי הרכב</button><button class="btn" onclick="toggleSave('${esc(l.id)}')">${state.saved.includes(l.id)?'נשמר ✓':'שמור'}</button><button class="btn ghost" onclick="ignoreCar('${esc(l.id)}')">התעלם</button></div></div></article>`}
function visible(){const q=($('#filterText')?.value||'').toLowerCase(),p=+($('#filterPrice')?.value||0),s=+($('#filterScore')?.value||0),seller=$('#filterSeller')?.value||'';return state.listings.filter(l=>!state.ignored.includes(l.id)).filter(l=>!q||`${l.make} ${l.model} ${l.trim||''}`.toLowerCase().includes(q)).filter(l=>!p||l.price<=p).filter(l=>(l.score||0)>=s).filter(l=>!seller||l.seller===seller).sort((a,b)=>(b.score||0)-(a.score||0))}
function render(){const list=visible();$('#listingsGrid').innerHTML=list.length?list.map(card).join(''):'<div class="panel empty">לא נמצאו מודעות.</div>';$('#dashboardListings').innerHTML=list.slice(0,4).map(card).join('');$('#mNew').textContent=state.listings.filter(x=>x.status==='חדש').length;$('#mDeals').textContent=state.listings.filter(x=>(x.score||0)>=80).length;$('#mSaved').textContent=state.saved.length;const ds=state.listings.map(discount);$('#mDiscount').textContent=(ds.length?ds.reduce((a,b)=>a+b,0)/ds.length:0).toFixed(1)+'%';renderSearches();renderAlerts();renderMarket();status();save()}
function renderSearches(){const e=$('#searchesList');e.innerHTML=state.searches.length?state.searches.map(s=>`<div class="search-item"><div><strong>${esc(s.name)}</strong><div class="muted small"><bdi>${esc(s.make||'')} ${esc(s.model||'')}</bdi> · עד ${s.maxPrice?money(s.maxPrice):'ללא הגבלה'}</div></div><div class="actions"><button class="btn" onclick="runSearch('${s.id}')">בדוק עכשיו</button><button class="btn danger" onclick="deleteSearch('${s.id}')">מחק</button></div></div>`).join(''):'<div class="empty">עדיין אין חיפושים שמורים.</div>'}
function renderAlerts(){$('#alertsList').innerHTML=state.alerts.length?state.alerts.slice().reverse().map(a=>`<div class="alert-item"><div><strong>${esc(a.title)}</strong><div class="muted small">${esc(a.text)}</div></div><small>${esc(a.time)}</small></div>`).join(''):'<div class="empty">אין התראות.</div>'}
function renderMarket(){if(!state.listings.length)return;const ps=state.listings.map(x=>+x.price).sort((a,b)=>a-b),avg=ps.reduce((a,b)=>a+b,0)/ps.length,mid=ps[Math.floor(ps.length/2)],mi=state.listings.reduce((a,b)=>a+(+b.mileage||0),0)/state.listings.length,sc=state.listings.reduce((a,b)=>a+(+b.score||0),0)/state.listings.length;$('#marketMedian').textContent=money(mid);$('#marketAverage').textContent=money(avg);$('#marketMileage').textContent=num(Math.round(mi))+' ק"מ';$('#marketScore').textContent=Math.round(sc)+'/100';const min=Math.min(...ps),max=Math.max(...ps),r=Math.max(1,max-min);$('#marketChart').innerHTML=ps.map((p,i)=>`<div class="bar" style="height:${35+(p-min)/r*110}px" title="${money(p)}"><span>${i+1}</span></div>`).join('');$('#priceHistory').innerHTML=state.history.length?state.history.slice().reverse().map(h=>`<div class="history-row"><strong>${esc(h.car)}</strong><div><span class="negative">${money(h.oldPrice)}</span> ← <span class="positive">${money(h.newPrice)}</span></div></div>`).join(''):'<div class="empty">עדיין לא זוהו ירידות מחיר.</div>'}
async function status(){const base=state.settings.serverUrl?.replace(/\/$/,'');$('#serverState').textContent=base||'לא הוגדר';$('#sourceStatus').textContent=base?'מחובר לשרת נתונים':'מצב מקומי';if(!base){$('#telegramState').textContent='נדרש שרת נתונים';return}try{const d=await (await fetch(base+'/api/integrations/status')).json();$('#telegramState').textContent=d.telegramConfigured?'מחובר ומוכן לשליחה':'ממתין להגדרה';$('#leviState').textContent=d.leviAuthorizedApiConfigured?'API מורשה מחובר':'מחירון ידני או חציון שוק'}catch{$('#telegramState').textContent='השרת לא זמין'}}
function nav(p){$$('.page').forEach(x=>x.classList.add('hidden'));$('#page-'+p).classList.remove('hidden');$$('[data-nav]').forEach(x=>x.classList.toggle('active',x.dataset.nav===p));scrollTo(0,0)}
$$('[data-nav]').forEach(b=>b.onclick=()=>nav(b.dataset.nav));$$('[data-open-search]').forEach(b=>b.onclick=()=>$('#searchModal').classList.remove('hidden'));$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('.modal').classList.add('hidden'));
$('#searchForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),s={id:'s-'+Date.now(),name:f.get('name'),make:f.get('make'),model:f.get('model'),yearMin:+f.get('yearMin')||null,yearMax:+f.get('yearMax')||null,maxPrice:+f.get('maxPrice')||null,maxMileage:+f.get('maxMileage')||null,sourceUrl:f.get('sourceUrl')||'',active:true};state.searches.push(s);if(state.settings.serverUrl)try{await api('/api/searches','POST',s)}catch{}e.target.reset();$('#searchModal').classList.add('hidden');toast('החיפוש נשמר');render()};
window.toggleSave=id=>{state.saved=state.saved.includes(id)?state.saved.filter(x=>x!==id):[...state.saved,id];render()};window.ignoreCar=id=>{state.ignored.push(id);toast('המודעה הוסתרה');render()};window.deleteSearch=id=>{state.searches=state.searches.filter(x=>x.id!==id);render()};
window.details=id=>{const l=state.listings.find(x=>x.id===id);if(!l)return;$('#detailContent').innerHTML=`<button class="close" onclick="$('#detailModal').classList.add('hidden')">×</button><h2><bdi>${esc(l.make)} ${esc(l.model)}</bdi></h2><div class="car-image">${carArt()}</div><div class="metrics"><div class="metric"><small>מחיר מבוקש</small><strong>${money(l.price)}</strong></div><div class="metric"><small>מחיר מחירון</small><strong>${money(l.referencePrice)}</strong></div><div class="metric"><small>חציון שוק</small><strong>${money(l.marketMedian||l.price)}</strong></div><div class="metric"><small>ציון עסקה</small><strong>${l.score}/100</strong></div></div><div class="analysis">המחיר ${discount(l)>=0?'נמוך':'גבוה'} ב-${Math.abs(discount(l)).toFixed(1)}% ממחיר המחירון. קילומטראז': ${num(l.mileage)} ק"מ, יד ${l.hand||'-'}, ${esc(l.location||'')}.</div><div class="actions"><button class="btn primary" onclick="openUrl('${esc(l.sourceUrl||'')}')">פתח מודעה</button><button class="btn" onclick="toggleSave('${esc(l.id)}')">שמור</button></div>`;$('#detailModal').classList.remove('hidden')};
window.openUrl=url=>{if(!url)return toast('לא קיים קישור למודעה');window.AutoDealNative?.openUrl?window.AutoDealNative.openUrl(url):window.open(url,'_blank','noopener')};
async function api(path,method='GET',body){const base=state.settings.serverUrl?.replace(/\/$/,'');if(!base)throw Error('no_server');const r=await fetch(base+path,{method,headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(d.error||'server');return d}
function merge(items){for(const n of items||[]){const o=state.listings.find(x=>x.id===n.id);if(o&&+n.price<+o.price){state.history.push({car:`${n.make} ${n.model}`,oldPrice:o.price,newPrice:n.price});state.alerts.push({title:'ירידת מחיר',text:`${n.make} ${n.model}: ${money(n.price)}`,time:'עכשיו'})}if(o)Object.assign(o,n);else{state.listings.unshift(n);state.alerts.push({title:'מודעה חדשה',text:`${n.make} ${n.model} ב-${money(n.price)}`,time:'עכשיו'})}}render()}
window.runSearch=async id=>{const s=state.searches.find(x=>x.id===id);if(!s)return;try{const d=await api('/api/search/run','POST',s);merge(d.listings);toast(`נמצאו ${d.listings?.length||0} מודעות`)}catch{if(s.sourceUrl)openUrl(s.sourceUrl);else toast('יש להגדיר שרת נתונים')}};
$('#refreshBtn').onclick=async()=>{try{merge((await api('/api/listings')).listings);toast('הנתונים עודכנו')}catch{toast('הנתונים המקומיים מעודכנים')}};['#filterText','#filterPrice','#filterScore','#filterSeller'].forEach(s=>$(s).oninput=render);
$('#serverConfig').onclick=()=>{const v=prompt('הזן כתובת שרת AutoDeal',state.settings.serverUrl||'');if(v!==null){state.settings.serverUrl=v.trim();render()}};
$('#telegramConfig').onclick=async()=>{const botToken=prompt('הדבק Bot Token שקיבלת מ-BotFather','');if(!botToken)return;const chatId=prompt('Chat ID. אם אינו ידוע, שלח לבוט הודעה והשאר ריק','');try{if(chatId)await api('/api/integrations/telegram','POST',{botToken,chatId});else await api('/api/integrations/telegram/discover-chat','POST',{botToken});toast('Telegram חובר בהצלחה');status()}catch{toast('לא הצלחנו לחבר את Telegram')}};
$('#testTelegram').onclick=async()=>{try{const d=await api('/api/telegram/test','POST');toast(d.ok?'הודעת בדיקה נשלחה':'Telegram אינו מוגדר')}catch{toast('בדיקת Telegram נכשלה')}};
$('#testYad2').onclick=async()=>{const url=prompt('הדבק קישור לחיפוש רכבים ציבורי ביד2','https://www.yad2.co.il/vehicles/cars');if(!url)return;try{const d=await api('/api/yad2/import','POST',{url});merge((await api('/api/listings')).listings);toast(`נמצאו ${d.found||0} מודעות`)}catch{toast('לא הצלחנו לקרוא את עמוד יד2')}};
$('#leviConfig').onclick=async()=>{const apiUrl=prompt('כתובת API מורשה של ספק המחירון','');if(!apiUrl)return;const apiKey=prompt('API Key','');if(!apiKey)return;try{await api('/api/integrations/levi','POST',{apiUrl,apiKey});toast('ספק המחירון חובר');status()}catch{toast('החיבור נכשל')}};
$('#manualPrice').onclick=async()=>{const make=prompt('יצרן','Toyota'),model=prompt('דגם','RAV4'),year=+prompt('שנתון','2023'),referencePrice=+String(prompt('מחיר מחירון','')).replace(/\D/g,'');if(!make||!model||!year||!referencePrice)return;try{await api('/api/pricebook/import','POST',{items:[{make,model,year,referencePrice,source:'מחירון שהוזן ידנית'}]});toast('מחיר המחירון נשמר')}catch{toast('השמירה נכשלה')}};
$('#requestNotify').onclick=async()=>{if(!('Notification'in window))return toast('המכשיר לא תומך בהתראות');toast((await Notification.requestPermission())==='granted'?'ההתראות הופעלו':'לא ניתנה הרשאה')};
$('#exportData').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='autodeal-backup.json';a.click()};$('#resetData').onclick=()=>{if(confirm('למחוק את כל נתוני AutoDeal מהמכשיר?')){Object.keys(localStorage).filter(k=>k.startsWith('autodeal.')).forEach(k=>localStorage.removeItem(k));location.reload()}};
if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('sw.js').catch(()=>{});render();
