window.AUTO_DEAL_CAR_CATALOG = [
  {name:'Toyota',he:'טויוטה',models:[['Yaris','יאריס'],['Yaris Cross','יאריס קרוס'],['Corolla','קורולה'],['Corolla Cross','קורולה קרוס'],['C-HR','C-HR'],['RAV4','RAV4'],['Camry','קאמרי'],['Prius','פריוס'],['Land Cruiser','לנד קרוזר'],['Aygo X','אייגו X']]},
  {name:'Hyundai',he:'יונדאי',models:[['i10','i10'],['i20','i20'],['i30','i30'],['Elantra','אלנטרה'],['Kona','קונה'],['Tucson','טוסון'],['Santa Fe','סנטה פה'],['Ioniq','איוניק'],['Ioniq 5','איוניק 5'],['Ioniq 6','איוניק 6']]},
  {name:'Kia',he:'קיה',models:[['Picanto','פיקנטו'],['Rio','ריו'],['Stonic','סטוניק'],['Niro','נירו'],['Sportage','ספורטאז׳'],['Sorento','סורנטו'],['Ceed','סיד'],['EV3','EV3'],['EV6','EV6']]},
  {name:'Mazda',he:'מאזדה',models:[['2','2'],['3','3'],['6','6'],['CX-3','CX-3'],['CX-30','CX-30'],['CX-5','CX-5'],['CX-60','CX-60']]},
  {name:'Skoda',he:'סקודה',models:[['Fabia','פאביה'],['Scala','סקאלה'],['Octavia','אוקטביה'],['Kamiq','קאמיק'],['Karoq','קארוק'],['Kodiaq','קודיאק'],['Superb','סופרב'],['Enyaq','אניאק']]},
  {name:'Volkswagen',he:'פולקסווגן',models:[['Polo','פולו'],['Golf','גולף'],['T-Cross','T-Cross'],['T-Roc','T-Roc'],['Tiguan','טיגואן'],['Passat','פאסאט'],['ID.3','ID.3'],['ID.4','ID.4']]},
  {name:'Seat',he:'סיאט',models:[['Ibiza','איביזה'],['Arona','ארונה'],['Leon','לאון'],['Ateca','אטקה']]},
  {name:'Cupra',he:'קופרה',models:[['Formentor','פורמנטור'],['Leon','לאון'],['Born','בורן'],['Tavascan','טאוואס קאן']]},
  {name:'Nissan',he:'ניסאן',models:[['Micra','מיקרה'],['Juke','ג׳וק'],['Qashqai','קשקאי'],['X-Trail','אקס טרייל'],['Sentra','סנטרה'],['Leaf','ליף']]},
  {name:'Mitsubishi',he:'מיצובישי',models:[['Space Star','ספייס סטאר'],['ASX','ASX'],['Eclipse Cross','אקליפס קרוס'],['Outlander','אאוטלנדר'],['L200','L200']]},
  {name:'Suzuki',he:'סוזוקי',models:[['Ignis','איגניס'],['Swift','סוויפט'],['Baleno','בלנו'],['Vitara','ויטרה'],['S-Cross','S-Cross'],['Jimny','ג׳ימני']]},
  {name:'Honda',he:'הונדה',models:[['Jazz','ג׳אז'],['Civic','סיוויק'],['HR-V','HR-V'],['CR-V','CR-V'],['ZR-V','ZR-V']]},
  {name:'Subaru',he:'סובארו',models:[['Impreza','אימפרזה'],['XV','XV'],['Crosstrek','קרוסטרק'],['Forester','פורסטר'],['Outback','אאוטבק'],['BRZ','BRZ']]},
  {name:'Renault',he:'רנו',models:[['Clio','קליאו'],['Captur','קפצ׳ור'],['Arkana','ארקנה'],['Austral','אוסטרל'],['Megane E-Tech','מגאן E-Tech']]},
  {name:'Peugeot',he:'פיג׳ו',models:[['208','208'],['2008','2008'],['308','308'],['3008','3008'],['5008','5008']]},
  {name:'Citroen',he:'סיטרואן',models:[['C3','C3'],['C3 Aircross','C3 איירקרוס'],['C4','C4'],['C5 Aircross','C5 איירקרוס']]},
  {name:'Opel',he:'אופל',models:[['Corsa','קורסה'],['Mokka','מוקה'],['Astra','אסטרה'],['Grandland','גרנדלנד']]},
  {name:'Ford',he:'פורד',models:[['Fiesta','פיאסטה'],['Focus','פוקוס'],['Puma','פומה'],['Kuga','קוגה'],['Explorer','אקספלורר'],['Mustang','מוסטנג']]},
  {name:'Chevrolet',he:'שברולט',models:[['Spark','ספארק'],['Cruze','קרוז'],['Trax','טראקס'],['Equinox','אקווינוקס'],['Traverse','טראוורס'],['Tahoe','טאהו']]},
  {name:'BMW',he:'ב.מ.וו',models:[['1 Series','סדרה 1'],['2 Series','סדרה 2'],['3 Series','סדרה 3'],['4 Series','סדרה 4'],['5 Series','סדרה 5'],['X1','X1'],['X2','X2'],['X3','X3'],['X5','X5'],['iX1','iX1']]},
  {name:'Mercedes-Benz',he:'מרצדס',models:[['A-Class','A-Class'],['C-Class','C-Class'],['E-Class','E-Class'],['CLA','CLA'],['GLA','GLA'],['GLB','GLB'],['GLC','GLC'],['GLE','GLE'],['EQA','EQA'],['EQB','EQB']]},
  {name:'Audi',he:'אאודי',models:[['A1','A1'],['A3','A3'],['A4','A4'],['A5','A5'],['Q2','Q2'],['Q3','Q3'],['Q4 e-tron','Q4 e-tron'],['Q5','Q5']]},
  {name:'Volvo',he:'וולוו',models:[['EX30','EX30'],['XC40','XC40'],['XC60','XC60'],['XC90','XC90'],['S60','S60'],['S90','S90']]},
  {name:'Tesla',he:'טסלה',models:[['Model 3','מודל 3'],['Model Y','מודל Y'],['Model S','מודל S'],['Model X','מודל X']]},
  {name:'BYD',he:'BYD',models:[['Dolphin','דולפין'],['Atto 3','אטו 3'],['Seal','סיל'],['Seal U','סיל U'],['Tang','טאנג']]},
  {name:'Geely',he:'ג׳ילי',models:[['Geometry C','ג׳אומטרי C'],['EX5','EX5']]},
  {name:'MG',he:'MG',models:[['MG3','MG3'],['ZS','ZS'],['HS','HS'],['MG4','MG4'],['Marvel R','Marvel R']]},
  {name:'Chery',he:'צ׳רי',models:[['Tiggo 4','טיגו 4'],['Tiggo 7','טיגו 7'],['Tiggo 8','טיגו 8'],['FX','FX']]}
];