import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const ROOT=path.dirname(fileURLToPath(import.meta.url));
const DATA=path.join(ROOT,'data','db.json');
const SETTINGS=path.join(ROOT,'data','settings.json');
const PORT=Number(process.env.PORT||8787);
const origin=process.env.ALLOWED_ORIGIN||'*';
const readJson=(f,fallback)=>{try{return JSON.parse(fs.readFileSync(f,'utf8'))}catch{return fallback}};
const writeJson=(f,v)=>{fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,JSON.stringify(v,null,2))};
const load=()=>readJson(DATA,{listings:[],searches:[],history:[],pricebook:[]});
const save=db=>writeJson(DATA,db);
const loadSettings=()=>({...readJson(SETTINGS,{}),telegramBotToken:process.env.TELEGRAM_BOT_TOKEN||readJson(SETTINGS,{}).telegramBotToken||'',telegramChatId:process.env.TELEGRAM_CHAT_ID||readJson(SETTINGS,{}).telegramChatId||'',leviApiUrl:process.env.LEVI_API_URL||readJson(SETTINGS,{}).leviApiUrl||'',leviApiKey:process.env.LEVI_API_KEY||readJson(SETTINGS,{}).leviApiKey||''});
const publicSettings=()=>{const s=loadSettings();return{telegramConfigured:!!(s.telegramBotToken&&s.telegramChatId),leviAuthorizedApiConfigured:!!(s.leviApiUrl&&s.leviApiKey)}};
function json(res,code,data){res.writeHead(code,{'content-type':'application/json; charset=utf-8','access-control-allow-origin':origin,'access-control-allow-headers':'content-type','access-control-allow-methods':'GET,POST,OPTIONS'});res.end(JSON.stringify(data))}
async function body(req){let x='';for await(const c of req)x+=c;if(!x)return{};return JSON.parse(x)}
const median=a=>{const x=a.filter(Number.isFinite).sort((a,b)=>a-b);return x.length?x[Math.floor(x.length/2)]:0};
function marketMedian(db,l){return median(db.listings.filter(x=>String(x.make).toLowerCase()===String(l.make).toLowerCase()&&String(x.model).toLowerCase()===String(l.model).toLowerCase()&&Math.abs((+x.year||0)-(+l.year||0))<=1).map(x=>+x.price))}
function score(l){const ref=+l.referencePrice||+l.marketMedian||0;if(!ref||!l.price)return 60;const d=(ref-l.price)/ref;return Math.max(0,Math.min(100,Math.round(72+d*180-(+l.mileage||0)/12000+(+l.year-2020)*1.5)))}
function normalize(x={}){return{id:String(x.id||x.itemId||x.adNumber||`ad-${Date.now()}-${Math.random().toString(36).slice(2,7)}`),make:String(x.make||x.manufacturer||''),model:String(x.model||''),trim:String(x.trim||x.subModel||''),year:+x.year||0,price:+String(x.price||0).replace(/\D/g,''),mileage:+String(x.mileage||x.kilometers||0).replace(/\D/g,''),hand:+x.hand||0,location:String(x.location||x.city||''),seller:String(x.seller||x.sellerType||'מוכר פרטי'),fuel:String(x.fuel||''),status:String(x.status||'חדש'),sourceUrl:String(x.sourceUrl||x.url||''),published:String(x.published||'עכשיו')}}
async function referencePrice(db,l){const s=loadSettings();if(s.leviApiUrl&&s.leviApiKey){try{const r=await fetch(s.leviApiUrl,{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${s.leviApiKey}`,'x-api-key':s.leviApiKey},body:JSON.stringify({make:l.make,model:l.model,trim:l.trim,year:l.year,mileage:l.mileage,hand:l.hand})});if(r.ok){const d=await r.json();const p=+(d.referencePrice||d.price||d.value||0);if(p)return{price:p,source:'API מחירון מורשה'}}}catch{}}
 const p=db.pricebook.find(x=>x.make.toLowerCase()===l.make.toLowerCase()&&x.model.toLowerCase()===l.model.toLowerCase()&&+x.year===+l.year);if(p)return{price:+p.referencePrice,source:p.source||'מחירון שהוזן ידנית'};const m=marketMedian(db,l);return{price:m,source:m?'חציון שוק (חלופה)':''}}
async function telegram(text){const s=loadSettings();if(!s.telegramBotToken||!s.telegramChatId)return{ok:false,error:'not_configured'};try{const r=await fetch(`https://api.telegram.org/bot${s.telegramBotToken}/sendMessage`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({chat_id:s.telegramChatId,text,disable_web_page_preview:false})});const d=await r.json();return{ok:!!d.ok,error:d.description||''}}catch(e){return{ok:false,error:e.message}}}
async function discoverChat(token){const r=await fetch(`https://api.telegram.org/bot${token}/getUpdates`);const d=await r.json();const m=[...(d.result||[])].reverse().find(x=>x.message?.chat?.id||x.channel_post?.chat?.id);return m?{ok:true,chatId:String(m.message?.chat?.id||m.channel_post?.chat?.id)}:{ok:false,error:'no_chat_found'}}
function collectObjects(v,out){if(!v||typeof v!=='object')return;if(Array.isArray(v)){for(const x of v)collectObjects(x,out);return}out.push(v);for(const x of Object.values(v))collectObjects(x,out)}
async function fetchYad2(url){const u=new URL(url);if(!/(^|\.)yad2\.co\.il$/i.test(u.hostname)||!u.pathname.startsWith('/vehicles/'))throw Error('not_yad2_url');const r=await fetch(u,{headers:{'user-agent':'Mozilla/5.0 AutoDeal/1.0','accept-language':'he-IL,he;q=0.9','accept':'text/html'}});if(!r.ok)throw Error(`yad2_http_${r.status}`);const html=await r.text();if(/captcha|verify you are human|access denied|robot/i.test(html))throw Error('yad2_blocked');const objs=[];for(const m of html.matchAll(/<script[^>]*type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)){try{collectObjects(JSON.parse(m[1]),objs)}catch{}}const out=[];for(const o of objs){if(!o||typeof o!=='object')continue;const price=o.offers?.price||o.price;const name=o.name||'';if(!price||!name)continue;const parts=String(name).split(/\s+/);const l=normalize({id:o.sku||o.productID||o.url,make:o.brand?.name||parts[0],model:parts.slice(1).join(' '),price,sourceUrl:o.url||u.toString(),image:Array.isArray(o.image)?o.image[0]:o.image});if(l.make&&l.model)out.push(l)}return out}
async function importListings(items,notify=true){const db=load();let created=0,updated=0,dropped=0;for(const raw of items){const n=normalize(raw),ref=await referencePrice(db,n);n.referencePrice=ref.price;n.referenceSource=ref.source;n.marketMedian=marketMedian(db,n);n.score=+raw.score||score(n);const old=db.listings.find(x=>x.id===n.id);if(old){if(n.price&&old.price&&n.price<old.price){db.history.push({car:`${n.make} ${n.model}`,oldPrice:old.price,newPrice:n.price,date:new Date().toISOString()});dropped++;if(notify)await telegram(`ירידת מחיר 🚗\n${n.make} ${n.model}\n${old.price.toLocaleString('he-IL')} ₪ ← ${n.price.toLocaleString('he-IL')} ₪\n${n.sourceUrl}`)}Object.assign(old,n);updated++}else{db.listings.unshift(n);created++;if(notify)await telegram(`נמצאה מודעה חדשה 🚗\n${n.make} ${n.model} ${n.year}\nמחיר: ${n.price.toLocaleString('he-IL')} ₪\nציון עסקה: ${n.score}/100\n${n.sourceUrl}`)}}save(db);return{created,updated,dropped,total:db.listings.length}}
function matches(l,s){return(!s.make||l.make.toLowerCase().includes(String(s.make).toLowerCase()))&&(!s.model||l.model.toLowerCase().includes(String(s.model).toLowerCase()))&&(!s.maxPrice||l.price<=s.maxPrice)&&(!s.maxMileage||!l.mileage||l.mileage<=s.maxMileage)&&(!s.yearMin||l.year>=s.yearMin)&&(!s.yearMax||l.year<=s.yearMax)}
async function runSearch(s,notify=true){let fetched=0,providerError='';if(s.sourceUrl){try{const list=await fetchYad2(s.sourceUrl);fetched=list.length;if(list.length)await importListings(list,notify)}catch(e){providerError=e.message}}return{listings:load().listings.filter(l=>matches(l,s)),fetched,providerError}}
async function poll(){const db=load();for(const s of db.searches.filter(x=>x.active!==false))try{await runSearch(s,true);s.lastRun=new Date().toISOString()}catch(e){s.lastError=e.message}save(db)}
const server=http.createServer(async(req,res)=>{try{if(req.method==='OPTIONS')return json(res,204,{});const u=new URL(req.url,`http://${req.headers.host}`);if(req.method==='GET'&&u.pathname==='/health')return json(res,200,{ok:true,service:'AutoDeal Server'});if(req.method==='GET'&&u.pathname==='/api/integrations/status')return json(res,200,publicSettings());if(req.method==='POST'&&u.pathname==='/api/integrations/telegram'){const p=await body(req),s=loadSettings();s.telegramBotToken=String(p.botToken||s.telegramBotToken||'');s.telegramChatId=String(p.chatId||s.telegramChatId||'');writeJson(SETTINGS,s);return json(res,200,{ok:true,...publicSettings()})}if(req.method==='POST'&&u.pathname==='/api/integrations/telegram/discover-chat'){const p=await body(req),d=await discoverChat(String(p.botToken||''));if(d.ok){const s=loadSettings();s.telegramBotToken=p.botToken;s.telegramChatId=d.chatId;writeJson(SETTINGS,s)}return json(res,d.ok?200:400,d)}if(req.method==='POST'&&u.pathname==='/api/integrations/levi'){const p=await body(req),s=loadSettings();s.leviApiUrl=String(p.apiUrl||'');s.leviApiKey=String(p.apiKey||'');writeJson(SETTINGS,s);return json(res,200,{ok:true,...publicSettings()})}if(req.method==='GET'&&u.pathname==='/api/listings')return json(res,200,{listings:load().listings});if(req.method==='POST'&&u.pathname==='/api/yad2/import'){const p=await body(req),list=await fetchYad2(String(p.url||'')),r=await importListings(list,p.notify!==false);return json(res,200,{ok:true,found:list.length,...r})}if(req.method==='GET'&&u.pathname==='/api/searches')return json(res,200,{searches:load().searches});if(req.method==='POST'&&u.pathname==='/api/searches'){const p=await body(req),db=load(),s={...p,id:String(p.id||`s-${Date.now()}`),active:p.active!==false},old=db.searches.find(x=>x.id===s.id);old?Object.assign(old,s):db.searches.push(s);save(db);return json(res,200,{ok:true,search:s})}if(req.method==='POST'&&u.pathname==='/api/search/run'){const p=await body(req);return json(res,200,{ok:true,...await runSearch(p,true)})}if(req.method==='POST'&&u.pathname==='/api/pricebook/import'){const p=await body(req),db=load();for(const x of p.items||[]){const item={make:String(x.make||''),model:String(x.model||''),year:+x.year,referencePrice:+x.referencePrice,source:String(x.source||'מחירון שהוזן ידנית')};const old=db.pricebook.find(y=>y.make.toLowerCase()===item.make.toLowerCase()&&y.model.toLowerCase()===item.model.toLowerCase()&&+y.year===item.year);old?Object.assign(old,item):db.pricebook.push(item)}save(db);return json(res,200,{ok:true,count:db.pricebook.length})}if(req.method==='POST'&&u.pathname==='/api/telegram/test')return json(res,200,await telegram('AutoDeal מחובר בהצלחה ✅'));if(req.method==='GET'&&u.pathname==='/api/history')return json(res,200,{history:load().history});return json(res,404,{ok:false,error:'not_found'})}catch(e){return json(res,400,{ok:false,error:e.message||'server_error'})}});
server.listen(PORT,'0.0.0.0',()=>console.log(`AutoDeal server listening on http://0.0.0.0:${PORT}`));setInterval(()=>poll().catch(console.error),Math.max(5,Number(process.env.POLL_MINUTES||15))*60000);
